### ISSUE TITLE
Unselect all in Confirmed Case Trajectories by Districts graph

### ISSUE THREAD

**Issue by sumeshpremraj** [c19k/website-src-production#18]
Thanks for all your hard work maintaining this website, it has been really useful.

Can you consider adding an unselect all option in the districts graph, it would be really useful to have. I want to see stats for my own district alone and having to unselect the other 8 districts takes a lot of time when this is done daily.

**Comment by nishad** [comment]
The Trajectories graph is drawn with a charting library c3.js. This feature comes with the library. We will try to resolve this, but unfortunately, there is no time frame for a fix. Feel free to issue a pull request, if possible.

**Comment by sumeshpremraj** [comment]
Closing this issue - unselect all feature exists with alt+click, found this in a closed c3js PR. 

https://github.com/c3js/c3/pull/1533

**Comment by nishad** [comment]
Thank you for mentioning it, we will try to add a short description in the website to use the <kbd>atl</kbd>+<kbd>click</kbd> to hide all.
