### ISSUE TITLE
Ernakulam District Boundary Issue

### ISSUE THREAD

**Issue by manojkmohan** [c19k/website-src-production#39]
ഫേസ്ബുക്കിൽ നമ്മുടെ പുതിയ ഹോട്ട്സ്പോട്ട് + ഡിസ്ട്രിക്റ്റ് ബൌണ്ടറി  അപ്ഡേറ്റുമായി ബന്ധപ്പെട്ട് പോസ്റ്റിട്ടപ്പോഴാണ് [എറണാകുളം ജില്ലയുടെ അതിർത്തിയ്ക്ക് ](https://www.facebook.com/manoj.k.mohan/posts/10217196068520225?comment_id=10217196266805182)പ്രശ്നമുണ്ടെന്ന് ഒരു സുഹൃത്ത് കമന്റ് ചെയ്തത്. നോക്കിയപ്പോൾ സംഭവം ശരിയാണ്. 2006ൽ ഇടുക്കി ജില്ലയിലെ കുട്ടമ്പുഴ പഞ്ചായത്തിനെ എറണാകുളത്തോടൊപ്പം ചേർത്തിരുന്നു. [സജാദിന്റെ മാപ്പിൽ](https://github.com/geohacker/kerala/tree/master/shapefiles) അത് പുതുക്കിയിട്ടില്ല. കൈവശമുണ്ടായിരുന്ന മറ്റുമാപ്പുകൾ ഉപയോഗിച്ച് തിരുത്തി, നിലവിൽ ഉപയോഗിക്കുന്ന ആട്രിബ്യൂഷൻ ടേബിൾ കൂടി ചേർത്ത് ഒരു താൽക്കാലിക ആവശ്യത്തിനുള്ള മാപ്പ് കൂടെ ചേർക്കുന്നു. 
[kuttampuzha fixed map.zip](https://github.com/c19k/website-src-production/files/4576846/kuttampuzha.fixed.map.zip)

**Comment by nishad** [comment]
ജിയോജെസൺന്റെ ഫയൽ വലുപ്പം അൽപ്പം കൂടുതലായതുകൊണ്ട് തൽക്കാലം പെന്റിങ്ങിൽ വച്ചിരുന്നതായിരുന്നു. https://github.com/c19k/website-src-production/pull/41 ഈ അപ്ഡേറ്റിൽ ലൈവ് വെബ്സൈറ്റിലേക്ക് ചേർത്തിട്ടുണ്ട്. സന്തോഷം :)
